"""프로젝트 전역 상수 정의"""

# 피드 파싱
EMPTY_FEED_SENTINEL = "no exist data"
BOARD_CONTENT_CLASS = "hwp_editor_board_content"

# 본문 수집
MAX_ARTICLE_BODY_LENGTH = 500
MAX_IMAGES_PER_ARTICLE = 3
IMAGE_DOWNLOAD_TIMEOUT = 10

# 첨부파일
ATTACHMENT_DOWNLOAD_TIMEOUT = 30
MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024  # 10MB
# Gemini에 바이너리로 직접 전달할 수 있는 파일 확장자
GEMINI_NATIVE_EXTENSIONS = {".pdf", ".jpg", ".jpeg", ".png", ".gif", ".webp"}

# 상태 관리
STATE_RETENTION_DAYS = 90

# 네트워크 타임아웃 (초)
FEED_FETCH_TIMEOUT = 15
ARTICLE_BODY_TIMEOUT = 10

# 동시 요청 제한
MAX_CONCURRENT_IMAGE_DOWNLOADS = 5
MAX_CONCURRENT_ATTACHMENT_DOWNLOADS = 3

# Gemini 배치 크기
GEMINI_BATCH_SIZE = 10

# 텔레그램
MAX_TELEGRAM_MESSAGE_LENGTH = 4096
